const sampleCards = [
    {
      "_id": "601215b8a2e6dc225fafee30",
      "index": 0,
      "guid": "b59a3c33-9dc8-4ead-b847-a3115e17c889",
      "isActive": false,
      "balance": "$2,968.69",
      "picture": "http://placehold.it/32x32",
      "age": 22,
      "eyeColor": "brown",
      "name": "Bowman Burton",
      "gender": "male",
      "company": "KEEG",
      "email": "bowmanburton@keeg.com",
      "phone": "+1 (853) 414-2995",
      "address": "481 Lloyd Court, Vernon, Florida, 1570",
      "about": "Adipisicing in ipsum quis magna tempor est qui. Deserunt excepteur in eiusmod ullamco. Commodo amet sunt exercitation veniam incididunt id esse labore reprehenderit reprehenderit. Amet exercitation in sunt mollit.\r\n",
      "registered": "2017-04-08T04:24:23 -10:00",
      "latitude": 7.491617,
      "longitude": -54.054155,
      "tags": [
        "est",
        "amet",
        "magna",
        "cillum",
        "eiusmod",
        "consectetur",
        "quis"
      ],
      "greeting": "Hello, Bowman Burton! You have 5 unread messages."
    },
    {
      "_id": "601215b8064a5047ab0803af",
      "index": 1,
      "guid": "aa0ef105-f60c-4660-bfd6-b05f00eea3e4",
      "isActive": true,
      "balance": "$2,755.72",
      "picture": "http://placehold.it/32x32",
      "age": 25,
      "eyeColor": "brown",
      "name": "Guerrero Wolf",
      "gender": "male",
      "company": "ROOFORIA",
      "email": "guerrerowolf@rooforia.com",
      "phone": "+1 (906) 413-3399",
      "address": "206 Amboy Street, Coinjock, South Carolina, 5954",
      "about": "Eu dolor duis non dolor ipsum ad amet exercitation in Lorem dolore cupidatat deserunt. Deserunt nisi ipsum esse fugiat sunt eiusmod amet ipsum labore dolore do amet excepteur cillum. Qui cillum consequat aliquip quis dolor eiusmod nulla exercitation anim tempor. Commodo incididunt ut cillum cupidatat officia laboris. Aliquip minim dolore elit dolor in tempor nulla consectetur aliquip velit sit incididunt excepteur. Irure ad ullamco ad reprehenderit consequat et dolore adipisicing mollit.\r\n",
      "registered": "2014-03-11T02:34:16 -10:00",
      "latitude": -47.295811,
      "longitude": -56.241103,
      "tags": [
        "laboris",
        "consequat",
        "eu",
        "amet",
        "cupidatat",
        "Lorem",
        "eiusmod"
      ],
      "greeting": "Hello, Guerrero Wolf! You have 10 unread messages."
    },
    {
      "_id": "601215b897b6b061cea28f7d",
      "index": 2,
      "guid": "888cceb5-465b-44f6-a061-f3eaa3f65578",
      "isActive": false,
      "balance": "$2,555.49",
      "picture": "http://placehold.it/32x32",
      "age": 20,
      "eyeColor": "brown",
      "name": "Monique Keith",
      "gender": "female",
      "company": "EXODOC",
      "email": "moniquekeith@exodoc.com",
      "phone": "+1 (958) 470-2218",
      "address": "289 Plymouth Street, Woodburn, Pennsylvania, 2571",
      "about": "In deserunt laborum in aute Lorem deserunt excepteur voluptate laboris. Proident nostrud Lorem laboris ipsum eiusmod ipsum. Fugiat incididunt est pariatur nisi excepteur nisi aliquip dolore est sit Lorem. Adipisicing ea ea ullamco Lorem anim anim laborum ipsum anim do nulla. Occaecat aute sint labore nulla est Lorem non minim fugiat.\r\n",
      "registered": "2015-12-04T09:14:54 -10:00",
      "latitude": -23.4754,
      "longitude": 2.826789,
      "tags": [
        "dolor",
        "occaecat",
        "laboris",
        "consequat",
        "nulla",
        "fugiat",
        "aliquip"
      ],
      "greeting": "Hello, Monique Keith! You have 7 unread messages."
    },
    {
      "_id": "601215b87932d818b7254f64",
      "index": 3,
      "guid": "f405b4ce-b655-467c-a063-d90090ec7d7a",
      "isActive": true,
      "balance": "$2,779.03",
      "picture": "http://placehold.it/32x32",
      "age": 33,
      "eyeColor": "green",
      "name": "Pam Wilkinson",
      "gender": "female",
      "company": "VETRON",
      "email": "pamwilkinson@vetron.com",
      "phone": "+1 (947) 439-3650",
      "address": "493 Indiana Place, Caspar, Wyoming, 7253",
      "about": "Cupidatat aute excepteur nulla irure ullamco culpa quis quis nostrud veniam. Mollit minim esse irure velit aliquip non culpa ipsum mollit consectetur. Amet qui aliquip quis esse sint qui. Sint quis dolor proident ex sunt consectetur velit dolor consequat. Cillum enim non cillum exercitation exercitation laboris ut do officia.\r\n",
      "registered": "2020-07-23T05:28:25 -10:00",
      "latitude": 20.55635,
      "longitude": -63.107387,
      "tags": [
        "eiusmod",
        "labore",
        "est",
        "consequat",
        "est",
        "proident",
        "in"
      ],
      "greeting": "Hello, Pam Wilkinson! You have 1 unread messages."
    },
    {
      "_id": "601215b858cd929a5edbddd6",
      "index": 4,
      "guid": "bf159b5d-9b0f-4908-8b79-af7e8776d173",
      "isActive": false,
      "balance": "$1,038.90",
      "picture": "http://placehold.it/32x32",
      "age": 21,
      "eyeColor": "green",
      "name": "Calhoun Shannon",
      "gender": "male",
      "company": "BIOHAB",
      "email": "calhounshannon@biohab.com",
      "phone": "+1 (997) 508-3182",
      "address": "772 Jackson Street, Davenport, Texas, 6513",
      "about": "Pariatur sit esse tempor voluptate duis voluptate magna. Irure voluptate ea aliquip consectetur sint. Sint sit exercitation irure ad magna qui irure aliqua nostrud magna ut veniam adipisicing. Commodo cupidatat culpa eiusmod tempor.\r\n",
      "registered": "2017-07-12T10:31:06 -10:00",
      "latitude": -59.502366,
      "longitude": 79.760129,
      "tags": [
        "qui",
        "pariatur",
        "quis",
        "amet",
        "amet",
        "amet",
        "tempor"
      ],
      "greeting": "Hello, Calhoun Shannon! You have 1 unread messages."
    },
    {
      "_id": "601215b83f33fe2965692560",
      "index": 5,
      "guid": "0b36621a-65aa-4968-8fdd-e3b8eac31c11",
      "isActive": false,
      "balance": "$1,163.12",
      "picture": "http://placehold.it/32x32",
      "age": 37,
      "eyeColor": "green",
      "name": "Allison Powers",
      "gender": "male",
      "company": "SYNKGEN",
      "email": "allisonpowers@synkgen.com",
      "phone": "+1 (985) 524-2224",
      "address": "155 Monaco Place, Frierson, New Jersey, 3245",
      "about": "Dolore deserunt fugiat Lorem ullamco labore cillum. Ea cupidatat aliqua dolore eu incididunt laboris commodo veniam labore sint anim labore dolore proident. Eu qui ad id consectetur dolore sunt quis ex enim enim irure id ex. In adipisicing elit et anim adipisicing ipsum et laboris consectetur non aliquip ex veniam qui. Nisi ut commodo dolore reprehenderit ea fugiat excepteur reprehenderit minim. Consectetur anim velit veniam et enim esse nulla. Reprehenderit elit ea laborum velit aliqua ad.\r\n",
      "registered": "2019-05-22T07:20:52 -10:00",
      "latitude": 82.121452,
      "longitude": 69.882794,
      "tags": [
        "nisi",
        "in",
        "eu",
        "laboris",
        "anim",
        "mollit",
        "laboris"
      ],
      "greeting": "Hello, Allison Powers! You have 7 unread messages."
    },
    {
      "_id": "601215b8bcdc5862c8d8222c",
      "index": 6,
      "guid": "950cc5a1-301c-4d51-bb18-5a7b91f32c0f",
      "isActive": true,
      "balance": "$1,846.21",
      "picture": "http://placehold.it/32x32",
      "age": 40,
      "eyeColor": "blue",
      "name": "Stella Hernandez",
      "gender": "female",
      "company": "THREDZ",
      "email": "stellahernandez@thredz.com",
      "phone": "+1 (941) 578-3568",
      "address": "509 Menahan Street, Ilchester, Maine, 5982",
      "about": "Non nostrud aute deserunt non tempor nisi consequat. Eu fugiat sint ut commodo. Nulla proident ullamco eu id minim quis est. Dolore dolore magna magna voluptate voluptate nostrud sunt. Cupidatat dolore Lorem labore et aliquip. Deserunt adipisicing eu eu dolor non veniam id laboris aliqua. Do Lorem occaecat culpa eu.\r\n",
      "registered": "2017-10-07T12:51:41 -10:00",
      "latitude": -54.969557,
      "longitude": -67.279629,
      "tags": [
        "qui",
        "ipsum",
        "consequat",
        "anim",
        "cupidatat",
        "elit",
        "anim"
      ],
      "greeting": "Hello, Stella Hernandez! You have 3 unread messages."
    },
    {
      "_id": "601215b8b369101cd828da73",
      "index": 7,
      "guid": "51aa611e-13c0-43c6-9fb0-d4767b2706c8",
      "isActive": true,
      "balance": "$1,895.96",
      "picture": "http://placehold.it/32x32",
      "age": 37,
      "eyeColor": "green",
      "name": "Lopez Buckley",
      "gender": "male",
      "company": "QUARX",
      "email": "lopezbuckley@quarx.com",
      "phone": "+1 (946) 411-2556",
      "address": "860 Greene Avenue, Reno, Indiana, 8365",
      "about": "Ad proident pariatur non eiusmod. Duis ea qui deserunt aliqua proident aliquip eiusmod. Irure excepteur do nostrud incididunt pariatur do sit voluptate eiusmod. Commodo veniam do reprehenderit nisi. Magna exercitation irure amet nulla culpa cupidatat labore adipisicing proident exercitation ipsum laboris minim. Id laborum commodo ex nulla eu culpa consequat.\r\n",
      "registered": "2020-09-27T05:20:22 -10:00",
      "latitude": -26.337142,
      "longitude": 152.597421,
      "tags": [
        "ea",
        "ad",
        "fugiat",
        "ut",
        "et",
        "sit",
        "veniam"
      ],
      "greeting": "Hello, Lopez Buckley! You have 2 unread messages."
    },
    {
      "_id": "601215b8ff7e1f185efd68f3",
      "index": 8,
      "guid": "3c8d947f-e1d4-4e1e-a2c7-0289ce337aae",
      "isActive": true,
      "balance": "$2,330.56",
      "picture": "http://placehold.it/32x32",
      "age": 37,
      "eyeColor": "blue",
      "name": "Pace Webb",
      "gender": "male",
      "company": "EXTRO",
      "email": "pacewebb@extro.com",
      "phone": "+1 (839) 425-2394",
      "address": "143 Aviation Road, Soham, Rhode Island, 5235",
      "about": "Magna nostrud labore enim do. Lorem elit ullamco exercitation cupidatat fugiat elit fugiat quis sint adipisicing mollit excepteur. Excepteur eu pariatur minim irure magna tempor minim ex. Culpa cupidatat magna ipsum officia ad et et aliqua voluptate irure quis non eu ipsum. Labore velit aliquip laborum ad enim sit laborum labore nisi. Aute commodo amet ea qui sint consequat ut consequat. Ullamco culpa duis laboris velit sunt velit irure aliquip id officia.\r\n",
      "registered": "2017-07-10T05:02:47 -10:00",
      "latitude": -86.915164,
      "longitude": 24.953457,
      "tags": [
        "et",
        "dolor",
        "consequat",
        "minim",
        "proident",
        "ad",
        "esse"
      ],
      "greeting": "Hello, Pace Webb! You have 2 unread messages."
    },
    {
      "_id": "601215b885740222a6c9ea8e",
      "index": 9,
      "guid": "40c5382f-2624-4195-ae97-863c7a8f6c98",
      "isActive": false,
      "balance": "$2,418.22",
      "picture": "http://placehold.it/32x32",
      "age": 21,
      "eyeColor": "blue",
      "name": "Stacey Mathews",
      "gender": "female",
      "company": "QUILK",
      "email": "staceymathews@quilk.com",
      "phone": "+1 (989) 555-2011",
      "address": "418 Hunterfly Place, Crown, Hawaii, 3538",
      "about": "Ut minim nostrud est eiusmod. Consectetur veniam officia eu labore in veniam aliquip. Sint aute sit quis do commodo ipsum sunt minim esse sit minim proident do reprehenderit.\r\n",
      "registered": "2018-07-26T02:14:54 -10:00",
      "latitude": -65.903319,
      "longitude": -115.334726,
      "tags": [
        "qui",
        "ut",
        "excepteur",
        "anim",
        "incididunt",
        "eiusmod",
        "exercitation"
      ],
      "greeting": "Hello, Stacey Mathews! You have 5 unread messages."
    },
    {
      "_id": "601215b8a76389a0d7777a46",
      "index": 10,
      "guid": "f21617f4-94bb-4555-9658-7f76665ee0cd",
      "isActive": false,
      "balance": "$3,325.03",
      "picture": "http://placehold.it/32x32",
      "age": 24,
      "eyeColor": "green",
      "name": "Joni Herman",
      "gender": "female",
      "company": "QUALITERN",
      "email": "joniherman@qualitern.com",
      "phone": "+1 (970) 599-2187",
      "address": "831 Reed Street, Ribera, Oklahoma, 8918",
      "about": "Voluptate tempor tempor eiusmod deserunt nostrud dolore. Dolor anim consectetur ea exercitation aute officia. Fugiat sunt labore tempor labore proident mollit enim. Veniam ut Lorem sint et aute nostrud incididunt proident aliquip dolor qui quis. Sint nisi labore ullamco est proident cillum enim Lorem enim ex. Esse et reprehenderit pariatur velit officia ad velit ipsum amet velit occaecat esse. Enim reprehenderit et anim qui excepteur consectetur laboris nisi laborum.\r\n",
      "registered": "2017-02-20T02:28:48 -10:00",
      "latitude": 14.118979,
      "longitude": 179.424788,
      "tags": [
        "irure",
        "aliqua",
        "cupidatat",
        "laboris",
        "mollit",
        "ipsum",
        "aliqua"
      ],
      "greeting": "Hello, Joni Herman! You have 2 unread messages."
    },
    {
      "_id": "601215b820a8f6f981d2e13d",
      "index": 11,
      "guid": "f0dbe3dd-9310-4d89-b2bf-c8fa48487cf8",
      "isActive": true,
      "balance": "$3,700.92",
      "picture": "http://placehold.it/32x32",
      "age": 27,
      "eyeColor": "blue",
      "name": "Hays Franks",
      "gender": "male",
      "company": "PERKLE",
      "email": "haysfranks@perkle.com",
      "phone": "+1 (976) 420-2144",
      "address": "270 Maple Avenue, Salunga, Marshall Islands, 8919",
      "about": "Sunt cillum ullamco voluptate cupidatat deserunt sint magna ad nisi cillum ut occaecat. Fugiat id aliqua labore velit enim Lorem elit in laboris tempor. Pariatur mollit in dolor commodo proident exercitation ullamco anim. Dolor quis amet pariatur ad nulla magna laborum. Adipisicing reprehenderit est consectetur fugiat officia.\r\n",
      "registered": "2014-05-12T01:37:44 -10:00",
      "latitude": -17.084054,
      "longitude": 68.435087,
      "tags": [
        "nulla",
        "commodo",
        "voluptate",
        "consequat",
        "dolore",
        "commodo",
        "veniam"
      ],
      "greeting": "Hello, Hays Franks! You have 6 unread messages."
    },
    {
      "_id": "601215b8fc1a75e13c437091",
      "index": 12,
      "guid": "b630c277-60b9-4db5-b968-2ced7c51d50c",
      "isActive": false,
      "balance": "$2,043.28",
      "picture": "http://placehold.it/32x32",
      "age": 26,
      "eyeColor": "brown",
      "name": "Mcdowell Cleveland",
      "gender": "male",
      "company": "UNQ",
      "email": "mcdowellcleveland@unq.com",
      "phone": "+1 (924) 552-3896",
      "address": "479 Furman Street, Elwood, Arkansas, 6625",
      "about": "Ex laboris aute excepteur voluptate pariatur consequat aliquip. Ut aliqua officia ad reprehenderit sunt irure ea ad. Sunt aliqua officia minim ex id. Et commodo aliqua excepteur deserunt est Lorem sit reprehenderit aliqua consectetur culpa cupidatat qui cupidatat. Ea in consectetur minim commodo.\r\n",
      "registered": "2014-11-23T09:38:54 -10:00",
      "latitude": -8.832845,
      "longitude": -34.084765,
      "tags": [
        "fugiat",
        "labore",
        "fugiat",
        "aliqua",
        "qui",
        "culpa",
        "amet"
      ],
      "greeting": "Hello, Mcdowell Cleveland! You have 9 unread messages."
    },
    {
      "_id": "601215b8dd36b4c2ca52aa76",
      "index": 13,
      "guid": "165b7fe6-8a84-4866-9edc-25b32075c99d",
      "isActive": true,
      "balance": "$1,616.18",
      "picture": "http://placehold.it/32x32",
      "age": 22,
      "eyeColor": "green",
      "name": "Manuela Boyle",
      "gender": "female",
      "company": "ZILLANET",
      "email": "manuelaboyle@zillanet.com",
      "phone": "+1 (861) 503-2482",
      "address": "302 Miami Court, Hall, New Mexico, 1908",
      "about": "Qui aliqua nulla proident reprehenderit ex dolor ea aliquip voluptate dolor est. Occaecat dolor non ut amet nulla. Labore id amet reprehenderit dolor proident nisi. Proident excepteur ullamco exercitation sit officia sit ullamco fugiat elit.\r\n",
      "registered": "2015-06-20T12:38:05 -10:00",
      "latitude": 59.825569,
      "longitude": -136.669557,
      "tags": [
        "commodo",
        "eiusmod",
        "nostrud",
        "nisi",
        "consectetur",
        "pariatur",
        "sint"
      ],
      "greeting": "Hello, Manuela Boyle! You have 4 unread messages."
    },
    {
      "_id": "601215b86d4a8c2d73c33e11",
      "index": 14,
      "guid": "10a6ef88-1872-4760-abb9-785fd8c56259",
      "isActive": false,
      "balance": "$2,352.36",
      "picture": "http://placehold.it/32x32",
      "age": 28,
      "eyeColor": "blue",
      "name": "Goldie Foster",
      "gender": "female",
      "company": "KLUGGER",
      "email": "goldiefoster@klugger.com",
      "phone": "+1 (994) 558-3441",
      "address": "129 Bokee Court, Ahwahnee, Louisiana, 5461",
      "about": "Dolor amet laboris culpa proident non laborum. Id ipsum voluptate eu cillum mollit mollit incididunt sit deserunt consequat magna tempor ullamco. Laborum laboris commodo veniam irure cupidatat anim ut. Do deserunt enim pariatur non in magna non irure duis adipisicing officia nisi tempor fugiat. Velit reprehenderit quis esse in sint in sunt nulla laborum. Amet deserunt qui amet incididunt ex commodo non.\r\n",
      "registered": "2018-01-31T07:16:25 -10:00",
      "latitude": -7.02934,
      "longitude": 159.15935,
      "tags": [
        "anim",
        "qui",
        "reprehenderit",
        "sit",
        "ea",
        "anim",
        "quis"
      ],
      "greeting": "Hello, Goldie Foster! You have 7 unread messages."
    },
    {
      "_id": "601215b88f2449347155a2dc",
      "index": 15,
      "guid": "a733886c-5235-435b-85ef-7e8178f0a461",
      "isActive": true,
      "balance": "$2,059.32",
      "picture": "http://placehold.it/32x32",
      "age": 32,
      "eyeColor": "blue",
      "name": "Rollins Petersen",
      "gender": "male",
      "company": "SNOWPOKE",
      "email": "rollinspetersen@snowpoke.com",
      "phone": "+1 (963) 479-3291",
      "address": "577 Clark Street, Cucumber, District Of Columbia, 9422",
      "about": "Nostrud qui tempor sit id. Laboris mollit ut deserunt ipsum laboris consectetur reprehenderit dolore excepteur. Veniam velit ex reprehenderit veniam ad excepteur Lorem ut nulla sunt veniam aliqua.\r\n",
      "registered": "2015-11-03T03:05:40 -10:00",
      "latitude": 35.337836,
      "longitude": 136.274187,
      "tags": [
        "qui",
        "nulla",
        "do",
        "esse",
        "commodo",
        "dolor",
        "mollit"
      ],
      "greeting": "Hello, Rollins Petersen! You have 7 unread messages."
    },
    {
      "_id": "601215b8b619492983f28f6a",
      "index": 16,
      "guid": "e8d187c5-d429-4a6a-880a-4f8262cef5a3",
      "isActive": true,
      "balance": "$2,667.11",
      "picture": "http://placehold.it/32x32",
      "age": 40,
      "eyeColor": "brown",
      "name": "William Flynn",
      "gender": "male",
      "company": "MARVANE",
      "email": "williamflynn@marvane.com",
      "phone": "+1 (970) 568-3498",
      "address": "889 Amersfort Place, Urie, North Carolina, 2247",
      "about": "Cupidatat incididunt est ex eu enim cillum amet ullamco officia sint ut eiusmod. Exercitation veniam cupidatat nulla ut culpa excepteur nostrud consectetur reprehenderit velit irure nostrud ad proident. Commodo deserunt dolor nostrud duis duis do eiusmod tempor consequat commodo aute laborum officia laboris. Pariatur cupidatat labore veniam amet. Adipisicing nulla tempor nulla cupidatat ullamco nulla voluptate laborum esse. Voluptate quis est consectetur dolore quis ea magna Lorem officia minim fugiat ipsum ex. Do reprehenderit amet dolore velit.\r\n",
      "registered": "2017-12-25T02:28:03 -10:00",
      "latitude": -74.507042,
      "longitude": 56.166329,
      "tags": [
        "magna",
        "et",
        "in",
        "mollit",
        "exercitation",
        "amet",
        "minim"
      ],
      "greeting": "Hello, William Flynn! You have 8 unread messages."
    }
  ]

  export default sampleCards;